### ISSUE TITLE
Lanyard: user not monitored | Script not detecting account id

### ISSUE THREAD

**Issue by HerXayah** [Hexality/osu-nowplaying#1]
![image](https://user-images.githubusercontent.com/45071533/231008014-6746b7d0-bc45-4cf3-a6b2-df7cf261dc2c.png)

**Comment by Hexality** [comment]
Are you in the Lanyard server?

**Comment by Hexality** [comment]
If you happen to be in the server and yet it isn't being able to gather your information, tell me later.

I may need to reactor this as this uses old code that I wrote back when I was learning PowerShell, so a lot of things may not be working correctly rn.


(Can't look onto it right now as I'm not in home)

**Comment by HerXayah** [comment]
I am indeed in the server.
I have my own website working with lanyard api :D

**Comment by Hexality** [comment]
The id is probably being wrongly passed to the script, I'll look into it later.
Thanks for the report!

**Comment by Hexality** [comment]
@PrincessAkira can you provide your id? I wanna test to see what is causing the error.
Also, I wanted to ask this before but forgot, which powershell version are you using?

**Comment by HerXayah** [comment]
> @PrincessAkira can you provide your id? I wanna test to see what is causing the error. Also, I wanted to ask this before but forgot, which powershell version are you using?

7.0 and my ID is `202740603790819328`

**Comment by Hexality** [comment]
![image](https://user-images.githubusercontent.com/17398632/231550352-7179cf6a-28e3-45d2-8e03-39bb09b6285b.png)
I'm currently rewritting it

**Comment by Hexality** [comment]
https://user-images.githubusercontent.com/17398632/231618005-606e7b73-5bad-4e1d-a518-68611a49b0fa.mp4

Almost done

**Comment by Hexality** [comment]
![image](https://user-images.githubusercontent.com/17398632/231618405-9d361cf2-4286-411c-a190-dbd68dce5c2d.png)

**Comment by Hexality** [comment]
@PrincessAkira [/releases](https://github.com/Hexality/osu-nowplaying/releases/tag/2.0.0)

**Comment by Hexality** [comment]
let me know if any error occurs
